configuration: Release

matrix:
    fast_finish: true

build_script:
    - git submodule update --init
    - Make.bat

test_script:
    - Make.bat test

artifacts:
    - path: luvit.exe

notifications:
    email: true
    irc: "irc.freenode.org#luvit"
